### ISSUE TITLE
添加代理问题

### ISSUE THREAD

**Issue by dfmjndm** [Soung2279/pica#1]
修改了pica.py中的代理
对man.py的request添加了代理  
rs = requests.get(url, headers=headers, timeout=(3.05, 27), stream=True,proxies={'http':'127.0.0.1:20171'})
但是res/img/pica/漫画名称/ 下没有图片资源，生成了一个20kb的压缩包，其余功能都可以使用

'看pica 605f6184df60c660e636f0df'
[2022-09-07 12:44:39,624 PICA] INFO: Message 1308101788 triggered get_pica.
pica获取失败,可能是输入id错误
压缩包创建完成:位于/hobot/res/img/pica/白雨想いてまざまざと (コミックホットミルク 2020年10月号).zip

**Comment by Yoruko-Sugar** [comment]
I reproduced same issue, waitng to check it.

**Comment by dfmjndm** [comment]
23/1/10  已解决，插件功能无问题，该功能对于网络要求较高，不建议大陆机器尝试
